### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Wissperwind** [odit-services/license-exporter#3]
```
license-exporter --json --recursive
node:buffer:400
function allocate(size) {
                 ^

RangeError: Maximum call stack size exceeded
    at allocate (node:buffer:400:18)
    at Function.allocUnsafe (node:buffer:377:10)
    at tryCreateBuffer (node:fs:427:21)
    at Object.readFileSync (node:fs:470:14)
    at parsePackageInfo (C:\Program Files\nodejs\node_modules\@odit\license-exporter\bin\exporter.js:46:40)
    at C:\Program Files\nodejs\node_modules\@odit\license-exporter\bin\exporter.js:60:23
    at Array.forEach (<anonymous>)
    at getDependencyLicenseInfo (C:\Program Files\nodejs\node_modules\@odit\license-exporter\bin\exporter.js:59:19)
    at C:\Program Files\nodejs\node_modules\@odit\license-exporter\bin\exporter.js:110:16
    at Array.forEach (<anonymous>)

Node.js v18.3.0
```

Anything to solve this?
Is my project too large? Can I increase the stack size?

**Comment by nicolaiort** [comment]
Hi @Wissperwind,

thanks for opening an issue.
Would you mind sharing your dependency list (we don't need the entire package.json)?
We'll try to reproduce your error and get back to you.

Greetings,
Nicolai

**Comment by Wissperwind** [comment]
Hi Nicolai,

Thanks for the fast response!
Here are our dependencies:
```
"dependencies": {
        "@emotion/react": "^11.10.6",
        "@emotion/styled": "^11.10.6",
        "@monaco-editor/react": "^4.4.6",
        "@mui/icons-material": "^5.11.11",
        "@mui/material": "^5.11.15",
        "@mui/x-date-pickers": "^6.0.3",
        "allotment": "^1.18.1",
        "axios": "^1.3.4",
        "dagre": "^0.8.5",
        "dayjs": "^1.11.7",
        "fast-xml-parser": "^4.1.3",
        "i18next": "^22.4.13",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-dropzone": "^14.2.3",
        "react-i18next": "^12.2.0",
        "react-json-tree": "^0.18.0",
        "react-router-dom": "^6.10.0",
        "react-syntax-highlighter": "^15.5.0",
        "reactflow": "^11.7.0",
        "universal-cookie": "^4.0.4",
        "uuid": "^9.0.0",
        "zustand": "^4.3.6"
    },
    "devDependencies": {
        "@types/dagre": "^0.7.48",
        "@types/react": "^18.0.31",
        "@types/react-dom": "^18.0.11",
        "@types/react-syntax-highlighter": "^15.5.6",
        "@types/uuid": "^9.0.1",
        "@vitejs/plugin-react": "^3.1.0",
        "@vitest/ui": "^0.29.8",
        "c8": "^7.13.0",
        "happy-dom": "^8.9.0",
        "typescript": "^5.0.2",
        "vite": "^4.2.1",
        "vite-tsconfig-paths": "^4.0.7",
        "vitest": "^0.29.8"
    }
```

**Comment by nicolaiort** [comment]
Thanks, I'll run some tests over the weekend.

**Comment by nicolaiort** [comment]
### Tests
We used the following test environment:
* node: 18.3.0
* package managers: npm, yarn, pnpm

### Results
We were able to reproduce the error with **npm** while using the `--recursive` flag.

### Consequences
The `--recursive` flag has to traverse large dependency trees. It was simply never meant for the "classic" react-scripts stack,
I'm gonna look into optimizing the logic used by `--recursive` and get back to you regarding potential solutions to your problem.

**Comment by nicolaiort** [comment]
We just released 0.1.0, it adds a `--depth` flag that allows you to controll the recusive submodule resolution.
I verified your project with depths up to 100.

The problem with dependency loops (a->b->c->a) will be also the main focus of another upcoming release.
You should be able to use license exporter in your project using the --depth flag r/n or you can wait for the next release.

**Comment by nicolaiort** [comment]
Well anyways: The new release arrived faster than expected ^^

0.2.0 resolves the propblem with dependency loops.
You should now be able to just call `license-exporter --json --recursive` without dealing with additional flags like `--depth`.

@Wissperwind Please test the license export in your project with version @odit/license-exporter:0.2.0

**Comment by Wissperwind** [comment]
problem solved, thank you!
